#pragma once
#include "Utils.h"

#define MAIN_LOOP_PERIOD 10
#define MOTOR_WHEEL_ACTUATION_PERIOD 100
#define MOTOR_WHEEL_ENCODER_PERIOD 20


#define TIMING_SETUP_SUCCESS 1  // will be set to 0 if conditions any else statements below are called

#if (MOTOR_WHEEL_ACTUATION_PERIOD % MAIN_LOOP_PERIOD == 0)
    #define MOTOR_WHEEL_ACTUATION_MOD (MOTOR_WHEEL_ACTUATION_PERIOD / MAIN_LOOP_PERIOD)
    #define MOTOR_WHEEL_SETUP_SUCCESS 1
#else
    #define TIMING_SETUP_SUCCESS 0
    #define MOTOR_WHEEL_SETUP_SUCCESS 0
#endif

#if (MOTOR_WHEEL_ENCODER_PERIOD % MAIN_LOOP_PERIOD == 0)
    #define MOTOR_WHEEL_ENCODER_MOD (MOTOR_WHEEL_ENCODER_PERIOD / MAIN_LOOP_PERIOD)
    #define MOTOR_WHEEL_ENCODER_SETUP_SUCCESS 1
#else
    #define TIMING_SETUP_SUCCESS 0
    #define MOTOR_WHEEL_ENCODER_SETUP_SUCCESS 0
#endif

int timing_setup_check();